import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/apis/sidebar";
import hardwareSidebar from "./docs/hardware/sidebar";

const sidebars: SidebarsConfig = {
  // hardwareSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'hardware',   // hardware location is docs/hardware
  //   },
  // ],
  hardwareSidebar,
  apiSidebar,
};

export default sidebars;
